name: Build Release APK

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - '.idea/*'
      - 'LICENSE'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - '.idea/*'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      - name: Build APK
        run: chmod +x ./gradlew && ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          path: app/build/outputs/apk/*
